"use client";

import { useState, useRef, ChangeEvent} from 'react';
import html2canvas from 'html2canvas';
import styles from '../styles/Home.module.css';
import Head from 'next/head';

export default function Home() {
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');
  const outputRef = useRef(null);

  const handleInputChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    setInputText(event.target.value);
    setOutputText(event.target.value);
  };

  const generateAndDownloadImage = () => {
    const element = outputRef.current;
    console.log(element)
    if (element) {
      html2canvas(element).then((canvas) => {
        canvas.toBlob((blob) => {
          if (blob) {
          const url = URL.createObjectURL(blob);
          const link = document.createElement('a');
          link.href = url;
          link.download = 'bratCover.png';
          link.click();
          URL.revokeObjectURL(url);
          }
        }, 'image/png');
      }); 
      
    }
  };


  return (
    <>
      <Head>
          <link rel="canonical" href="https://fridayblessings.me/" />
          <link rel="icon" href="/brat-generator.jpeg" type="image/jpeg" />
      </Head>
      <nav className={styles.navbar}>
        <ul className={styles.navList}>
          <li className={styles.navItem}><a href="/">Homepage</a></li>
          <li className={styles.navItem}><a href="/blog">Blog</a></li>
          <li className={styles.navItem}><a href="https://ko-fi.com/harvey888">Buy me a coffee</a></li>
        </ul>
      </nav>
      <div className={styles.container}>
        <h1 className={styles.title}>Free Brat Generator Image</h1>
        <textarea
          className={styles.textarea}
          placeholder="please input text..."
          value={inputText}
          onChange={handleInputChange}
        ></textarea>
        <button className={styles.button} onClick={generateAndDownloadImage}>Download Brat Image</button> 
        <div className={styles.outputText}  ref={outputRef} >{outputText}</div>
      </div>

      <div className={styles.description}>
        <h2>About Brat Generator</h2>
        <p>The Brat Generator is a tool designed to help you create unique and personalized images with ease. Whether you are looking to generate images for social media, blogs, or personal projects, the Brat Generator offers a simple and intuitive interface to get the job done.</p>
        <h3>Frequently Asked Questions</h3>
        <ul>
          <li>
            <strong>What is the Brat Generator?</strong>
            <p>The Brat Generator is an online tool that allows users to create custom images by inputting text and downloading the generated image.</p>
          </li>
          <li>
            <strong>How do I use the Brat Generator?</strong>
            <p>Simply enter your desired text into the input field, and click the "Download Brat Image" button to generate and download your custom image.</p>
          </li>
          <li>
            <strong>Is the Brat Generator free to use?</strong>
            <p>Yes, the Brat Generator is completely free to use.</p>
          </li>
          <li>
            <strong>Can I use the generated images for commercial purposes?</strong>
            <p>Yes, you can use the images generated by the Brat Generator for both personal and commercial purposes.</p>
          </li>
        </ul>
      </div>
      
      
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <div className={styles.footerLinks}>
            <h3>Friend Links</h3>
            <ul>
              <li><a href="https://tap4.ai" target="_blank" rel="noopener noreferrer">Tap4 AI</a></li>
            </ul>
          </div>
          <div className={styles.footerContact}>
            <p>Contact us at: <a href="mailto:harveybj2000@gmail.com">harveybj2000@gmail.com</a></p>
          </div>
        </div>
      </footer>
    </>
  );
}